# Generated by Django 5.0.6 on 2024-06-26 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="username",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 6, 26, 4, 52, 59, 734320, tzinfo=datetime.timezone.utc
                ),
                max_length=150,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
