# Generated by Django 5.0.6 on 2024-06-26 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userdata_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="userdata",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
