# Generated by Django 5.0.6 on 2024-06-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Riddles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.CharField(max_length=200)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "level 1"),
                            (2, "level 2"),
                            (3, "level 3"),
                            (4, "level 4"),
                            (5, "level 5"),
                            (6, "level 6"),
                            (7, "level 7"),
                            (8, "level 8"),
                            (9, "level 9"),
                            (10, "level 10"),
                        ]
                    ),
                ),
            ],
        ),
    ]
