# Generated by Django 5.0.6 on 2024-06-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riddles",
            name="question",
            field=models.TextField(),
        ),
    ]
