# Generated by Django 5.0.6 on 2024-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="trap_count",
            field=models.IntegerField(default=0),
        ),
    ]
