# Generated by Django 5.0.6 on 2024-06-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_riddles_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="riddles",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="riddles",
            name="is_trap",
            field=models.BooleanField(default=True),
        ),
    ]
