# Generated by Django 5.0.6 on 2024-06-27 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_userprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 6, 27, 14, 7, 49, 827995, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
