# Generated by Django 5.0.6 on 2024-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_level_alter_riddles_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("score", models.IntegerField(default=0)),
                ("password", models.CharField(max_length=30)),
                ("photo", models.CharField(max_length=200)),
            ],
        ),
    ]
